### ISSUE TITLE
Setup versions / changelog (https://github.com/atlassian/changesets)

### ISSUE THREAD

**Issue by Decipher** [druxt/druxt.js#136]

**Comment by Decipher** [comment]
I install `@changesets/cli` and followed the instructions as per https://www.npmjs.com/package/@changesets/cli

After running `yarn changeset` I get:

```sh
🦋  error Error: Failed to find where HEAD diverged from master. Does master exist?
🦋  error     at getDivergedCommit (/workspace/druxt.js/node_modules/@changesets/git/dist/git.cjs.dev.js:58:11)
🦋  error     at processTicksAndRejections (internal/process/task_queues.js:95:5)
🦋  error     at async getChangedFilesSince (/workspace/druxt.js/node_modules/@changesets/git/dist/git.cjs.dev.js:169:22)
🦋  error     at async Object.getChangedPackagesSinceRef (/workspace/druxt.js/node_modules/@changesets/git/dist/git.cjs.dev.js:208:24)
🦋  error     at async add (/workspace/druxt.js/node_modules/@changesets/cli/dist/cli.cjs.dev.js:462:29)
🦋  error     at async run$1 (/workspace/druxt.js/node_modules/@changesets/cli/dist/cli.cjs.dev.js:1153:11)
```

I suspect that is because the mono-repo hasn't been merged back into master.

Gitpod snapshot: https://gitpod.io#snapshot/d2096418-ace5-430c-b34f-10a510b399cf
