### ISSUE TITLE
Error when no SSR and API proxy enabled

### ISSUE THREAD

**Issue by Decipher** [druxt/druxt.js#526]
**Describe the bug**
When running DruxtSite in production with No SSR and the API proxy enabled, I receive the following error.

```
94b1367.js:2 TypeError: Cannot read properties of undefined (reading 'length')
    at f.render (e305641.js:2:13745)
    at t._render (94b1367.js:2:36072)
    at f.r (94b1367.js:2:65837)
    at kn.get (94b1367.js:2:27380)
    at kn.run (94b1367.js:2:28264)
    at En (94b1367.js:2:26363)
    at Array.<anonymous> (94b1367.js:2:12562)
    at ue (94b1367.js:2:12006)
```

**To Reproduce**
1. Go to https://gitpod.io/#https://github.com/druxt/quickstart-druxt-site
2. Wait
3. Update `nuxt.config.js`: `ssr: false`
4. Add `proxy: { api: true },` to `druxt` object in `nuxt.config.js`.
4. Run `npm run build && npm start`

**Expected behavior**
N/A

**Media**
N/A

**Your Environment (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by Decipher** [comment]
It seems that this issue is only caused when `druxt-site` is in `buildModules` not in `modules`.

**Comment by Decipher** [comment]
It's likely that this is a non-issue, as it's only client-side the modules are required at runtime, not just buildtime.
