### ISSUE TITLE
Node >= 17 error: ERR_OSSL_EVP_UNSUPPORTED

### ISSUE THREAD

**Issue by Decipher** [druxt/druxt.js#531]
**Describe the bug**
The following error occurs when running Node v17 or higher with Druxt:

```
node:internal/crypto/hash:67
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:130:10)
    at module.exports (.../node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (.../node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (.../node_modules/webpack/lib/NormalModule.js:471:10)
    at .../node_modules/webpack/lib/NormalModule.js:503:5
    at .../node_modules/webpack/lib/NormalModule.js:358:12
    at .../node_modules/webpack/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (.../node_modules/webpack/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at Array.<anonymous> (.../node_modules/webpack/node_modules/loader-runner/lib/LoaderRunner.js:205:4) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}
```

**To Reproduce**
1. Run a Druxt site using Node v17 or higher

**Expected behavior**
No errors.

**Media**
<img width="994" alt="image" src="https://user-images.githubusercontent.com/161090/178188064-915b0f61-6eb8-43af-9a4e-5efa442321e8.png">

**Your Environment (please complete the following information):**
Node v17

**Additional context**
N/A

**Comment by Decipher** [comment]
This appears to be a Nuxt / Webpack issue that won't be being resolved, but has a workaround:

https://github.com/webpack/webpack/issues/14532#issuecomment-947012063
```
export NODE_OPTIONS=--openssl-legacy-provider
```
