### ISSUE TITLE
Error in fetch(): input.include.split is not a function

### ISSUE THREAD

**Issue by Decipher** [druxt/druxt.js#73]
**Describe the bug**
When using the latest DruxtSite, DruxtBlocks and Druxt module I get the following error:

```
 ERROR  Error in fetch(): input.include.split is not a function

  at DrupalJsonApiParams.initializeWithQueryObject (/Users/stuartclark/Projects/Druxt/druxt-dev/druxt.js/node_modules/drupal-jsonapi-params/lib/index.js:118:47)
  at getDrupalJsonApiParams (/Users/stuartclark/Projects/Druxt/druxt-dev/druxt.js/dist/druxt.ssr.js:978:13)
  at Store.getCollection (/Users/stuartclark/Projects/Druxt/druxt-dev/druxt.js/dist/druxt.ssr.js:1159:27)
```

**To Reproduce**
1. Setup quickstart backend
2. Setup quickstart frontend with DruxtSite module
3. Add latest DruxtBlocks module
4. `npm run dev`

**Expected behavior**
No errors.

**Media**
N/A

**Your Environment (please complete the following information):**

**Additional context**
Appears to be related to the QueryObject that is made from the DrupalJsonApiParams object being incompatible with the expected input of the `DrupalJsonApiParams().initializeWithQueryObject()` method.

https://github.com/d34dman/drupal-jsonapi-params/blob/master/src/index.ts#L173-L175

**Comment by Decipher** [comment]
Fixed in 0.6.1.

Need to followup with `drupal-jsonapi-params`.
